#!/bin/bash
# Important this should be run from the directory that contains your dotfiles
# This script safely makes symlinks with dotfiles to keep all of my devices
# in sync. Before overwrriting any existing dotfiles with our new symlinked
# dotfiles, we make sure to move existing dotfiles into ~/dofiles_old
configfiles=".vimrc .gitconfig .zshrc .Xresources .aliases .exports .tmux.clipboard .tmux.conf .zshrc.local"

# Move any existing dotfiles in ~ to dotfiles_old directory and then create 
# symlinks for all listed $configfiles from this dotfiles directory.
dotfiles_old=~/dotfiles_old
mkdir -p $dotfiles_old
for file in $configfiles; do
    if [ -e ~/$file ]; then
        echo "Moving $file from ~/ to ~$dotfiles_old/"
        mv ~/$file $dotfiles_old
    fi
    echo "Creating symlink to $file in home directory."
    ln -s `pwd`/$file ~/$file
done

# Move I3 configs to backup and install new i3 config
mkdir -p .i3
echo "Moving I# config"
mv ~/.i3/config $dotfiles_old
mv ~/.i3/i3status.conf $dotfiles_old
ln -s `pwd`/.i3/config ~/.i3/config
ln -s `pwd`/.i3/i3status.conf ~/.i3/i3status.conf
